### ISSUE TITLE
Test AR vs. VAR on toy model of a VAR(3) process with and without seasonality

### ISSUE THREAD

**Issue by anton-pershin** [dynolab/networkts#21]
- [x] Create toy model generator for VAR processes and put it into networkts/toy_models.py
- [x] Create test "AR vs. VAR" on VAR(3) process
- [x] Create test "AR vs. VAR" on VAR(3) process augmented with seasonality (e.g., add lag 20)
- [x] Put both tests into tests/ directory

For both tests, demonstrate in-sample and out-of-sample forecasts and demonstrate that a VAR forecast is better in any case

**Comment by NikitaKnyazev** [comment]
Checking the adequacy of the VAR model is described in overleaf in subsection "Toy example of VAR(3) process with seasonal dummy variables":
https://www.overleaf.com/project/62440d88f66a4680e46f2cc8
