### ISSUE TITLE
Change fit() and predict() interface to (X, y) representation

### ISSUE THREAD

**Issue by dynolab** [dynolab/networkts#6]
Generally, X denotes exogeneous variables and y denotes endogeneous variables. Due to some features of sklearn interface, we have to use X even though it is often not needed. To make some sensible use of this situation, we could force the user to put always non-zero X containing at least one "feature" -- time. This would give us make sense of our time series -- they will always have sense of time

**Comment by anton-pershin** [comment]
List of files to changes:

- [ ] base.py
- [ ] cross_validation.py
- [ ] arima.py
- [ ] autoreg.py
- [ ] holtwinter.py
- [ ] lstm.py
- [ ] prophet.py
- [ ] xgboost.py
